name: Copy Files

on:
  push:
    branches:
      - source_branch

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: R14.0
          path: R14.0
      - name: Copy files
        run: cp R13.0/trigger.txt R14.0/copy/
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add R14.0/
          git commit -m "Copy files from R13.0"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: R14.0
          directory: R14.0
